[build]
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://example.netlify.app"

[functions]
  node_bundler = "esbuild"

# Optional: specify a custom edge functions directory at the root level (not under [build])
# edge_functions = "netlify/edge-functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
